apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: java-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/hopecatcher/maven-hellow-world.git
#    contextDir:
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: hello-world:latest
  triggers:
    - type: ConfigChange
